export const users = [
  { id: 1, username: 'anson', displayName: 'Anson' },
  { id: 2, username: 'carlos', displayName: 'Carlos' },
  { id: 3, username: 'mariana', displayName: 'Mariana' },
  { id: 4, username: 'emma', displayName: 'Emma' },
  { id: 5, username: 'jackson', displayName: 'Jackson' },
  { id: 6, username: 'sophia', displayName: 'Sophia' },
  { id: 7, username: 'liam', displayName: 'Liam' },
  { id: 8, username: 'olivia', displayName: 'Olivia' },
  { id: 9, username: 'william', displayName: 'William' },
  { id: 10, username: 'ava', displayName: 'Ava' },
  { id: 11, username: 'alexander', displayName: 'Alexander' },
  { id: 12, username: 'isabella', displayName: 'Isabella' },
  { id: 13, username: 'michael', displayName: 'Michael' },
  { id: 14, username: 'sophie', displayName: 'Sophie' },
  { id: 15, username: 'benjamin', displayName: 'Benjamin' },
  { id: 16, username: 'emily', displayName: 'Emily' },
  { id: 17, username: 'lucas', displayName: 'Lucas' },
  { id: 18, username: 'mia', displayName: 'Mia' },
  { id: 19, username: 'jayden', displayName: 'Jayden' },
  { id: 20, username: 'charlotte', displayName: 'Charlotte' },
];
