export const users = [
  { id: 1, username: 'anson', displayName: 'Anson', password: 'password1' },
  { id: 2, username: 'carlos', displayName: 'Carlos', password: 'password1' },
  { id: 3, username: 'mariana', displayName: 'Mariana', password: 'password1' },
  { id: 4, username: 'emma', displayName: 'Emma', password: 'password1' },
  { id: 5, username: 'jackson', displayName: 'Jackson', password: 'password1' },
  { id: 6, username: 'sophia', displayName: 'Sophia', password: 'password1' },
  { id: 7, username: 'liam', displayName: 'Liam', password: 'password1' },
  { id: 8, username: 'olivia', displayName: 'Olivia', password: 'password1' },
  { id: 9, username: 'william', displayName: 'William', password: 'password1' },
  { id: 10, username: 'ava', displayName: 'Ava', password: 'password1' },
  {
    id: 11,
    username: 'alexander',
    displayName: 'Alexander',
    password: 'password1',
  },
  {
    id: 12,
    username: 'isabella',
    displayName: 'Isabella',
    password: 'password1',
  },
  {
    id: 13,
    username: 'michael',
    displayName: 'Michael',
    password: 'password1',
  },
  { id: 14, username: 'sophie', displayName: 'Sophie', password: 'password1' },
  {
    id: 15,
    username: 'benjamin',
    displayName: 'Benjamin',
    password: 'password1',
  },
  { id: 16, username: 'emily', displayName: 'Emily', password: 'password1' },
  { id: 17, username: 'lucas', displayName: 'Lucas', password: 'password1' },
  { id: 18, username: 'mia', displayName: 'Mia', password: 'password1' },
  { id: 19, username: 'jayden', displayName: 'Jayden', password: 'password1' },
  {
    id: 20,
    username: 'charlotte',
    displayName: 'Charlotte',
    password: 'password1',
  },
];
